### ISSUE TITLE
Denver Egotist Job link is failing. 

### ISSUE THREAD

**Issue by danhannigan** [Denver-Devs/welcome-to-denver#21]
We've now got a bot checking URL's - problem is it's throwing an error on an actual URL.

```Issues :-(
> Links 
  1. [L40] 410 http://www.thedenveregotist.com/jobs  
```

Take a look, and feel free to toss up a PR if you have a solution. This could be an easy Hacktoberfest PR ;) 

Using:
+ Travis CI: https://travis-ci.org/Denver-Devs/welcome-to-denver.svg?branch=master
+ Awesome Bot: https://github.com/dkhamsing/awesome_bot

**Comment by dlinch** [comment]
#23 
I think this is a little more in depth than first meets the eye. I hit the uri manually using Net::HTTP (the same implementation as awesome_bot) as well as postman, and they both return 410. I did some digging, and it's possible denver egotist blacklisted certain types of requests (probably to prevent crawling of their jobs). 

The relevant stackoverflow issue: https://stackoverflow.com/questions/23659662/410-gone-error-after-wordpress-update

I put up the PR to whitelist #the denveregotist, otherwise I'm not sure this will ever pass because it's not an issue on awesome_bot's or travis' end.

**Comment by danhannigan** [comment]
Thanks for digging into it! I was leaning towards a whitelist response myself but wanted to open it up for Hacktoberfest tinkerers since it was one that I finally could. I like whatcha did and I'll merge it!
